version: '3'

services:
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    depends_on:
      - postgres
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    command:
      - start-dev
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - keycloak-network

  mailhog:
    image: mailhog/mailhog:v1.0.1
    expose:
      - 1025
      - 8025
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - keycloak-network
  
  openldap:
    image: bitnami/openldap:2.5
    environment:
      BITNAMI_DEBUG: "true"
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: admin
      LDAP_USERS: johnldap,jackldap,janeldap
      LDAP_PASSWORDS: johnldap,jackldap,janeldap
    expose:
      - 1389
    ports:
      - 8389:1389
    networks:
      - keycloak-network

networks:
  keycloak-network: